### ISSUE TITLE
Changes in OpenAI Assistants API v2

### ISSUE THREAD

**Issue by rtaylorzfin** [FlyBase/biocurator-assistant#2]
@christabone 
I'm curious if you've been working on any changes to match the recent v2 of the Assistants API (https://platform.openai.com/docs/assistants/migration)?  I was thinking of working on a pull request, but I don't want to duplicate any effort if you've already been working on it.

**Comment by christabone** [comment]
Hey @rtaylorzfin -- good question. I have actually refactored it in the Alliance repo: https://github.com/alliance-genome/agr_biocurator_assistant

I should probably archive this repo as all my changes will be in the Alliance repo moving forward.

I just pushed the changes last week. If you try it, please let me know if it gives you any issues or problems.

**Comment by christabone** [comment]
(I closed this but feel free to reply if necessary!)
